---
- name: Appying agent.conf configuration
  template:
    src: agent.conf.j2
    dest: /etc/dome9/agent.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dome9d

- name: Enable and start the dome9d service on boot
  service:
    enabled: yes
    name: dome9d
    state: started
...
