---
- name: Assert that the prerequisites are defined
  tags: dome9agent
  assert:
    that:
      - dome9_install_pairkey is defined
      - dome9_install_secgroups is defined

- name: Ensure that the Dome9Agent package is installed
  tags: dome9agent
  become: true
  yum:
    enablerepo: Dome9
    name: Dome9Agent
    state: present
  register: dome9agent_yum

- block:
    - name: Checking for a dome9agent client certificiate
      stat:
        path: /var/lib/dome9/client.pem
      register: dome9agent_stat

    - name: Executing dome9agent pairing tasks (if applicable)
      import_tasks: dome9agent_pairing.yml
      when: not dome9agent_stat.stat.exists

    - name: Executing dome9agent service tasks (if applicable)
      import_tasks: dome9agent_service.yml
      when: dome9agent_stat.stat.exists
  tags: dome9agent
  become: true
  when: dome9agent_yum|success
...
