---
- name: Assert that prerequisites exist
  tags: dome9agent
  assert:
    that:
      - dome9_install_pairkey is defined
      - dome9_install_secgroups is defined

- name: Ensure that the Dome9Agent package is installed
  tags: dome9agent
  become: true
  yum:
    enablerepo: Dome9
    name: Dome9Agent
    state: present
    update_cache: yes
  register: dome9_yum

- name: Determine if dome9d stamp has been generated
  tags: dome9agent
  become: true
  stat:
    path: /var/lib/dome9/stamp
  register: dome9_stat

- name: Executing dome9d with pairing settings
  tags: dome9agent
  become: true
  command: >
    dome9d pair
    -g "{{ dome9_install_secgroups|join(',') }}"
    -k "{{ dome9_install_pairkey }}"
    -s "{{ inventory_hostname }}"
  when:
    - not dome9_stat.stat.exists
    - dome9_yum|success

- block:
    - name: Appying agent.conf configuration
      template:
        src: agent.conf.j2
        dest: /etc/dome9/agent.conf
        owner: root
        group: root
        mode: 0644
      notify: restart dome9d

    - name: Enable the dome9d service on boot
      service:
        enabled: yes
        name: dome9d
  tags: dome9agent
  become: true
  when: dome9_yum|success
...
